# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Camify' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for Camify
  pod 'ImagePicker'
  use_frameworks!



  target 'CamifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CamifyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
